function varargout=plot_witkin(regions,varargin)
% Plots the ternary tree as done by Witkin 1984, Figure 4
%
%   plot_witkin( REGIONS ) plots the scale space regions bounded at the top
%   by the singular point where the defining zero crossing lines emerged,
%   at the bottom where another singular points splits a region in three,
%   on the sides by the positions where the zero crossing lines leave the 
%   scale space plane. REGIONS is generated by the function
%   scale_space_tree.
%
%   See also: scale_space_tree
%
%  Witkin, A. P. (1984), Scale-space filtering: A new approach to 
%    multi-scale description, in Acoustics, Speech, and Signal Processing,
%    IEEE International Conference on ICASSP ’84, vol. 9, pp. 150–153,
%    IEEE, doi:10.1109/ICASSP.1984.1172729

% The MIT License (MIT)
% 
% Copyright (c) 2016 Bart Vermeulen
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.

nargoutchk(0,1);

h=plot(regions(:,[3; 3; 4; 4; 3;])',regions(:,[1; 2; 2; 1; 1;])', varargin{:});

if nargout > 0
    varargout{1}=h;
end